name: ecommerce_moda
description: App mobile de ecommerce para moda em Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.0

  # State Management
  provider: ^6.0.0

  # Local Storage
  shared_preferences: ^2.2.0
  hive: ^2.2.0

  # UI
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.0
  video_player: ^2.9.2
  video_player_web: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/bannerMobile1.jpg
